# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [17]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [18]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
zero1=np.zeros(10)
print(zero1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
array1=np.array([1,2,3])
print(array1.nbytes)

24


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
zero2=np.zeros(10)
zero2[4]=1
print(zero2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vect1=np.arange(10, 50)
print(vect1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vect2=np.array([1,2,3])
rev_vector=vect2[::-1]

print(rev_vector)

[3 2 1]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix=np.arange(0,9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array2=np.array([1,2,0,0,4,0])
indices=np.nonzero(array2)
print(indices)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
identity_matrix=np.identity(3)
print(identity_matrix)

identity_matrix2=np.eye(3)
print(identity_matrix2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
random=np.random.random((3, 3, 3))
print(random)

[[[0.50338777 0.10891004 0.72653376]
  [0.49875962 0.21213693 0.152876  ]
  [0.35649137 0.59782435 0.7369218 ]]

 [[0.94994095 0.93074589 0.09609451]
  [0.49153208 0.95769165 0.00462849]
  [0.52286364 0.66033021 0.70105144]]

 [[0.19896443 0.62616407 0.37704525]
  [0.82785551 0.37848829 0.65544977]
  [0.14486066 0.28792175 0.70329215]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
random2=np.random.random((10, 10))

min=random2.min()
max=random2.max()

print(random2, min, max)

[[0.87718313 0.05093143 0.27542924 0.69572446 0.22605162 0.1110907
  0.42025713 0.1387399  0.90048799 0.0897759 ]
 [0.67606495 0.34781301 0.07256989 0.46052256 0.58793255 0.05782997
  0.0011147  0.28083975 0.93222234 0.51731094]
 [0.6937017  0.10848592 0.86531484 0.95478105 0.15893052 0.2569978
  0.62388756 0.64984585 0.20380932 0.47320467]
 [0.55255099 0.55201544 0.93405419 0.58951962 0.00100803 0.08236365
  0.48406994 0.70873512 0.51250251 0.24282421]
 [0.02045517 0.02420456 0.91992268 0.76495346 0.05630173 0.04399777
  0.18994986 0.59367905 0.14439759 0.46832807]
 [0.4585202  0.21867737 0.26739114 0.01864514 0.60878251 0.39029098
  0.74607908 0.62476105 0.4904566  0.80647646]
 [0.32028278 0.88022786 0.35333903 0.7187381  0.98607009 0.28300808
  0.93099651 0.79931636 0.95859794 0.40030491]
 [0.95722019 0.40716823 0.96089675 0.56011503 0.1407094  0.62418991
  0.06665556 0.70543367 0.32215879 0.11972355]
 [0.78696566 0.35496224 0.08557646 0.81481776 0.90984103 0.03469766
  0.39802981 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
random3=np.random.random(30)
mean=random3.mean()
print(random3, mean)

[0.10094973 0.3423147  0.33686751 0.76419238 0.73096547 0.02408306
 0.81940232 0.08574405 0.90671154 0.56850999 0.47729985 0.05396057
 0.0418981  0.77346164 0.2820045  0.37299416 0.81868065 0.06985582
 0.78033493 0.07127686 0.44931727 0.91506436 0.43370269 0.7515849
 0.0692311  0.81287627 0.79723875 0.91112616 0.3631007  0.05371187] 0.4659487293022027


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
array2d=np.ones((5,5))
array2d[1:-1, 1:-1]=0
print(array2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [31]:
matrix=np.diag([1,2,3,4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
matrix=np.zeros((8,8))
matrix[1::2,::2]=1
matrix[::2,1::2]=1
print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [32]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [23]:
random=np.random.random((5,5))
mean=random.mean()
s=random.std()
Z=(random-mean)/s
print(Z)

[[-0.66112654  1.61185772 -0.98355743 -1.52939975  1.63541878]
 [ 0.03763875  1.64266001 -0.68456117 -0.32697999  0.22031432]
 [-1.42707417 -0.1429544  -0.12797091  1.42817448 -0.93130299]
 [ 0.78606776 -0.81670771  0.30165904 -0.61411552 -0.90231957]
 [ 0.95303925  1.09618808  0.75079895 -1.5447665   0.22901949]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [33]:
color=np.dtype([("r", np.ubyte, 1),
                ("g", np.ubyte, 1),
                ("b", np.ubyte, 1),
                ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-33-627837b5fd82>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r", np.ubyte, 1),


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
matrix=np.dot(np.random.random((5,3)), np.random.random((3,2)))
print(matrix)

[[0.60305174 0.40684354]
 [0.88561158 0.1571678 ]
 [0.64830434 0.28651825]
 [0.62699952 0.50315159]
 [0.83244713 0.31844245]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
array1d=np.arange(10)
array1d[(array1d>=3)&(array1d<=8)]=-array1d[(array1d>=3)&(array1d<=8)]
print(array1d)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


9,10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z**Z

2 << Z >> 2

Z <- Z

1j*Z

Z/1/1

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-30-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-30-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-30-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [35]:
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
np.intersect1d(Z1, Z2)

array([2, 3, 8, 9])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [36]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-36-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [37]:
Z=np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [41]:
A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [42]:
array=np.random.uniform(0,5,5)
print(array-array%1)
print(array//1)

[3. 2. 4. 0. 1.]
[3. 2. 4. 0. 1.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [43]:
matrix=np.zeros((5,5))
matrix+=np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [44]:
vect=np.random.random(10)
vect.sort()
print(vect)

[0.01480321 0.18878371 0.23519786 0.29061119 0.36521412 0.42935958
 0.43864946 0.62815802 0.74064227 0.93705031]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [45]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal=np.array_equal(A,B)
print(equal)

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [46]:
matrix=np.random.random((10,2))
X,Y=matrix[:,0], matrix[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.91788784 0.70183188 0.65553629 0.92570851 0.97455759 1.17581952
 0.31183114 0.67960745 0.56152348 1.20991949]
[0.64065427 0.1708261  1.02215892 0.58185111 1.45058428 0.68699377
 0.86940689 1.18035049 1.31659365 0.62840522]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [47]:
Z=np.random.random(10)
Z[Z.argmax()]=0
print(Z)

[0.42961181 0.45277581 0.31973747 0.         0.28513731 0.36344277
 0.02841764 0.72592071 0.16167243 0.19913868]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [48]:
Z = np.arange(100)
v = np.random.uniform(0,100)

index=(np.abs(Z-v)).argmin()
print(Z[index])

59


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [50]:
Z=np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
  print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [51]:
n=5
p=2
Z=np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [52]:
# column 2
Z = np.random.randint(0,10,(3,3))
sort=Z[Z[:,1].argsort()]
print(sort)

[[8 6 9]
 [9 7 2]
 [7 8 9]]


In [53]:
# column 3
Z = np.random.randint(0,10,(3,3))
sort=Z[Z[:,2].argsort()]
print(sort)

[[0 1 1]
 [7 9 8]
 [2 4 9]]
