#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [10]:
import numpy as np
A=np.random.random((5,3))
B=np.random.random((3,2))
print(np.dot(A,B))

[[0.16538869 0.38582559]
 [0.37612016 0.77627125]
 [0.44361821 0.89043452]
 [0.52213931 1.04740964]
 [0.5455338  1.06567232]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [12]:
array=np.arange(10)
array[(array>3)&(array<8)]*=-1
print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9 (-1+0+1+2+3+4의 합)

10 (0부터 4까지의 합)

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [17]:
Z=np.arange(9).reshape(3,3)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[[       1        1        4]
 [      27      256     3125]
 [   46656   823543 16777216]]
[[  0   1   2]
 [  4   8  16]
 [ 32  64 128]]
[[False False False]
 [False False False]
 [False False False]]
[[0.+0.j 0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j 0.+5.j]
 [0.+6.j 0.+7.j 0.+8.j]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

마지막으로 제외하고 legal하다.

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [18]:
print(np.array(0) / np.array(0)) #결과: nan
print(np.array(0) // np.array(0)) #결과: 0에 가까운 수
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-18-c43b556c15ef>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0)) #결과: nan
<ipython-input-18-c43b556c15ef>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) #결과: 0에 가까운 수
<ipython-input-18-c43b556c15ef>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [19]:
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 3 6 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [20]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-20-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [21]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [13]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [14]:
array=np.random.uniform(0,5,5)
print(array-array%1)
print(array//1)

[3. 2. 4. 2. 1.]
[3. 2. 4. 2. 1.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [15]:
matrix=np.zeros((5,5))
matrix+=np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [16]:
vect=np.random.random(10)
print(vect)
vect.sort()
print(vect)

[0.84111865 0.58835254 0.37780665 0.83939786 0.21232341 0.12363901
 0.40997891 0.14970108 0.44892508 0.23732677]
[0.12363901 0.14970108 0.21232341 0.23732677 0.37780665 0.40997891
 0.44892508 0.58835254 0.83939786 0.84111865]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [22]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

#방법1-Assuming identical shape of the arrays and a tolerance for the comparison of values
equal=np.allclose(A,B)
print(equal)

#방법2-Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal=np.array_equal(A,B)
print(equal)

False
False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [23]:
Z=np.random.random((10,2))
X,Y=Z[:,0], Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.94122259 0.98152958 0.21981836 0.56945783 1.21194404 0.98617799
 1.14892184 0.75018375 0.93470449 0.74098692]
[1.2666151  0.28903723 0.33467717 1.12516296 0.86817694 0.0419536
 0.67686587 0.54572965 0.4782592  1.41616245]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [24]:
Z=np.random.random(10)
Z[Z.argmax()]=0
print(Z)

[0.74211213 0.83700182 0.45856159 0.55678152 0.59203389 0.
 0.38554513 0.46174899 0.00897729 0.01386557]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [25]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index=(np.abs(Z-v)).argmin()
print(Z[index])

22


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [26]:
Z = np.arange(9).reshape(3,3)
#방법1
for index, value in np.ndenumerate(Z):
    print(index, value)
#방법2
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [27]:
n=10
p=3
Z=np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [28]:
#column 1
Z = np.random.randint(0,10,(3,3))

print(Z)
print(Z[Z[:,0].argsort()])

[[6 3 5]
 [6 1 2]
 [8 0 2]]
[[6 3 5]
 [6 1 2]
 [8 0 2]]


In [29]:
#column 2
print(Z)
print(Z[Z[:,1].argsort()])

[[6 3 5]
 [6 1 2]
 [8 0 2]]
[[8 0 2]
 [6 1 2]
 [6 3 5]]


In [30]:
#column 3
print(Z)
print(Z[Z[:,2].argsort()])

[[6 3 5]
 [6 1 2]
 [8 0 2]]
[[6 1 2]
 [8 0 2]
 [6 3 5]]
